lines = [
    "@echo off",
    "cd /d \"%~dp0\"",
    "color 0e",
    "",
    "set PROJ_DIR=%~dp0",
    "",
    "if \"%~1\"==\"\" (",
    "    echo.",
    "    echo  Usage: study.bat YYMMDD",
    "    echo  Example: study.bat 260401",
    "    echo.",
    "    pause",
    "    exit /b 1",
    ")",
    "",
    "set ARG=%~1",
    "set YEAR=20%ARG:~0,2%",
    "set MON=%ARG:~2,2%",
    "set DAY=%ARG:~4,2%",
    "set DATES=%YEAR%-%MON%-%DAY%",
    "",
    "echo.",
    "echo [STUDY] date  = %DATES%",
    "echo [STUDY] Launching 2 windows...",
    "echo.",
    "",
    r"set SIM_TMP=%TEMP%\mmean_sim_%RANDOM%.bat",
    "(",
    "    echo @echo off",
    "    echo :LOOP",
    "    echo call \"%PROJ_DIR%sim.bat\" %ARG%",
    "    echo goto LOOP",
    ") > \"%SIM_TMP%\"",
    "start \"MMEAN SIM [%DATES%]\" cmd /k \"%SIM_TMP%\"",
    "",
    "start \"MMEAN PULSE [%DATES%]\" cmd /k \"\\\"\" \"%PROJ_DIR%pulse_sim.bat\\\"\" %ARG%\"",
    "",
    "echo [STUDY] 2 windows started. Ctrl+C to stop each.",
    "echo.",
]
with open(r"C:\mmean\study.bat", "wb") as f:
    f.write(b"\r\n".join(line.encode("cp949") for line in lines))
print("OK")
